spring.application.name=ShoppingCart
spring.price.endpoint=https://equalexperts.github.io/backend-take-home-test-data/

spring.tax.percent=12.5

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true



